### ISSUE TITLE
Utilisation d'un chemin absolu au lieu de la variable d'environnement $HOME pour améliorer la portabilité

### ISSUE THREAD

**Issue by loisglld** [nath54/Dedale_LLM#1]
Je me permets de vous signaler, avec tout le respect dû à votre travail, que l'usage d'un chemin absolu tel que

```python
BASE_FILE_PART = "/home/nathan/Documents/"
```

n'est pas conforme aux meilleures pratiques de portabilité et d'adaptabilité du code, et qu'il serait judicieux de le remplacer par une référence dynamique à la variable d'environnement `$HOME`, ce qui permettrait d'accroître la **robustesse** et la **flexibilité** de votre script en le rendant compatible avec divers environnements utilisateurs.

Je vous passe bien le bonsoir.

PS: n'oubliez surtout pas de bien vous hydrater en ce temps de canicule.🥤

**Comment by aaalloc** [comment]
Здравствуйте, я могу подтвердить, что на моей машине это не работает из-за этого, и меня очень раздражает такая самодеятельность... Не могли бы вы исправить это быстро? Мне нужен этот код для запуска моего личного проекта.

**Comment by aaalloc** [comment]
#2

**Comment by loisglld** [comment]
Please consider merging this PR .......

PS : très TRÈS **déplacé** de parler russe sous cette issue @aaalloc ...

![buff](https://github.com/user-attachments/assets/0406a494-46b5-4ccb-ae1b-9870afe6e4f3)
